services:

  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # URL основного API-сервиса (укажите реальный адрес)
      BACKEND_URL: ${BACKEND_URL:-https://simulatorfordoctorsfastapi-api-production.up.railway.app/docs#/}

volumes: {}
